name: OWASP ZAP Security Scan

on:
  pull_request:
    branches:
      - main 

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0

      - name: Run ZAP Scan
        run: |
          docker run -v $(pwd):/zap/wrk -t owasp/zap2docker-weekly zap-baseline.py -t http://samantha.etiennethompson.com/