name: OWASP ZAP Security Scan

on:
  pull_request:
    branches:
      - main 

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create Directory for ZAP Reports
        run: mkdir -p /zap/wrk/

      - name: ZAP Scan
        run: |
             # Run your ZAP command here, specifying the necessary options for your scan
             # For example:
             /path/to/zap-baseline.py -t http://samantha.etiennethompson.com -J /zap/wrk/report_json.json -w /zap/wrk/report_md.md -r /zap/wrk/report_html.html
